title: 신근재
description: Android App 개발자
site_title: 'SGJ Portpolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: 신근재
blog_url: https://velog.io/@shin75492
email: shin75492.com
keybase_username: 신근재
twitter_username: 신근재_
reddit_username: 신근재

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 